version: '3.8'

services:
  summarizer:
    image: summarizer
    build: 
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./src:/app/src
    ports:
      - 8501:8501
    container_name: summarizer_app